// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwxijabYrIr3Ghj49S0KkeSn7hVhOTbvU',
    appId: '1:672573161716:web:ccf663308ac5c19a069ea1',
    messagingSenderId: '672573161716',
    projectId: 'yokoso-a0411',
    authDomain: 'yokoso-a0411.firebaseapp.com',
    storageBucket: 'yokoso-a0411.firebasestorage.app',
    measurementId: 'G-1ZJWNG71N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7XtkqHRw5DL8T0V78RIGkcKvogUks1q8',
    appId: '1:672573161716:android:81ac42d648c6c163069ea1',
    messagingSenderId: '672573161716',
    projectId: 'yokoso-a0411',
    storageBucket: 'yokoso-a0411.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwxijabYrIr3Ghj49S0KkeSn7hVhOTbvU',
    appId: '1:672573161716:web:b3d568b753775cf2069ea1',
    messagingSenderId: '672573161716',
    projectId: 'yokoso-a0411',
    authDomain: 'yokoso-a0411.firebaseapp.com',
    storageBucket: 'yokoso-a0411.firebasestorage.app',
    measurementId: 'G-Q83LWP67DY',
  );
}
